### ISSUE TITLE
Changes for stereo audio.

### ISSUE THREAD

**Issue by areebbashir** [jik876/hifi-gan#106]
Could you suggest some changes for stereo audio. I tried making some changes. Could you please suggest the changes for stereo sound.

**Comment by CookiePPP** [comment]
First off, why do you need stereo audio?
HiFi-GAN may already be capable of what you want or another option may exist

**Comment by areebbashir** [comment]
I have a dataset that is stereo. I have converted it to mono but I still wanted to make the changes for stereo. Due to the additional channel there is an additional dimension to handle. 
_AssertionError: 4D tensors expect 4 values for padding._

I tried making some changes but ended up with more errors.

**Comment by areebbashir** [comment]
I'm using pretrained models to generate the files. My next step is gonna be to train it on the dataset.

**Comment by CookiePPP** [comment]
I still do not understand the exact problem you're trying to solve by using stereo audio.

I'd recommend sticking to mono unless there is a serious reason. The spectrograms used as input for HiFi-GAN will also be mono, and HiFi-GAN is built to convert speech spectrograms to waveforms. Speech generally doesn't benefit from stereo since the left and right channel are almost identical.

If you need something like directional audio you can use something like https://github.com/facebookresearch/BinauralSpeechSynthesis which convert mono audio to stereo after synthesis.

---

(the reason I'm not really you how to make the changes is because there's a lot of changes required and you'd likely get no benefit from doing it)

**Comment by areebbashir** [comment]
OK thanks. Only reason for that is I wanted to make it general. I am getting new datasets regularly and I wanted to skip the step of conversion.
