### ISSUE TITLE
Can the MEL spectrum be resampled?

### ISSUE THREAD

**Issue by 980202006** [jik876/hifi-gan#40]
Hello, the model you provided has a strong generalization, but it is different from the sampling rate of my project. Is there any MEL resampling algorithm that can directly sample to the corresponding sampling rate, such as 48000Hz

**Comment by Miralan** [comment]
> Hello, the model you provided has a strong generalization, but it is different from the sampling rate of my project. Is there any MEL resampling algorithm that can directly sample to the corresponding sampling rate, such as 48000Hz

I don't know if there is a way of resampling MEL, MEL is lack of phase information. In the respect of raw wav, using traditional signal processing method is useless to resample lower frequency wav to higher frequency wav due to Nyquist–Shannon sampling theorem (High frequency part can not be recovered accurately).
Maybe some super-resolution algorithm based on DL can help you. But I really recommand you retrain a 48k version vocoder.

**Comment by 980202006** [comment]
thank you
