### ISSUE TITLE
Questions about MPD's ability to enhance MOS and contribution of feature-matching loss

### ISSUE THREAD

**Issue by francislata** [jik876/hifi-gan#64]
@jik876 This is more of a high-level question.

1) Table 4 of section 4.2 shows the application of MPD on MelGAN. I understand that HiFi-GAN and MelGAN uses MSD with almost the same settings. Have you done experiments with other GAN-based vocoders applying MPD and showed improvements in perceptual quality?

2) The feature-matching loss is used in the MSD by HiFi-GAN as well as MelGAN. Did you do any experiments with and without this loss and how it affects the perpetual quality?

Thank you!

**Comment by jik876** [comment]
Thank you for your interest.

1. We didn't conduct experiment with other models. Since the MPD takes raw waveform as the input and does not have any coupling with generator architecture, it will not be complicated to experiment with applying it to other models.

2. In our experiments, the feature matching loss affected perceptual quality. However, the quality degradation was different depending on datasets. Since the feature matching loss makes computation of backward operation heavy, it will be a good idea to experiment without it.

**Comment by Ziyi6** [comment]
@jik876 Hey, I plotted the feature mapping loss of mpd and msd while training and found out that these losses are increasing during training. Is it normal? I just used the config v1 and LJ speech dataset as training set. How can one understand this phenomenon?

<img width="1780" height="927" alt="Image" src="https://github.com/user-attachments/assets/c108c7f4-e619-4ab5-84fe-f61793b0d28a" />
